services:
  - type: web
    name: app-server
    env: docker
    plan: free
    dockerfilePath: ./backend/Dockerfile  
    envVars:
      - key: DATABASE_URL
        value: postgresql://postgres:qwerty@app-database:5432/deap_innov
    buildCommand: ""  
    startCommand: ""  

  - type: web
    name: app-database
    env: docker
    image: postgres:latest
    envVars:
      - key: POSTGRES_DB
        value: deap_innov
      - key: POSTGRES_PASSWORD
        value: qwerty
    plan: free
