services:
  - type: web
    name: app-server
    env: docker
    plan: free
    dockerfilePath: ./backend/Dockerfile  # Path to your Dockerfile for the server
    envVars:
      - key: DATABASE_URL
        value: postgresql://postgres:qwerty@app-database:5432/deap_innov
    buildCommand: ""  # Optional; can be removed if unused
    startCommand: ""  # Optional; can be removed if unused

  - type: web
    name: app-database
    env: docker
    image: postgres:13  # Using the official PostgreSQL image
    envVars:
      - key: POSTGRES_DB
        value: deap_innov
      - key: POSTGRES_PASSWORD
        value: qwerty
    plan: free
